---
# tasks file for kibana
- name: Install Kibana (Ubuntu)
  apt:
    name: kibana
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Run Daemon-Reload for Kibana (Ubuntu)
  systemd: daemon_reload=yes
  when: ansible_distribution == "Ubuntu"

- name: Enable Service Kibana (Ubuntu)
  systemd:
    name: kibana
    enabled: yes
  when: ansible_distribution == "Ubuntu"

- name: Install Kibana (CentOS)
  yum:
    name: kibana
    state: latest
    update_cache: yes
  when: ansible_distribution == "CentOS"

- name: Run Daemon-Reload for Kibana (CentOS)
  systemd: daemon_reload=yes
  when: ansible_distribution == "CentOS"

- name: Enable Service Kibana (CentOS)
  systemd:
    name: kibana
    enabled: yes
  when: ansible_distribution == "CentOS"
