---
# tasks file for elk
- name: Install Packages for ELK (Ubuntu)
  apt:
    name:
      - default-jre
      - nginx
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Add ELK APT Key (Ubuntu)
  apt_key:
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Add ELK Repository (Ubuntu)
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"
    state: present
    filename: "elasticsearch.list"
  when: ansible_distribution == "Ubuntu"

- name: Install Elasticsearch (Ubuntu)
  apt:
    name: elasticsearch
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Install packages for ELK (CentOS)
  yum:
    name:
      - java-11-openjdk
      - nginx
    state: latest
    update_cache: yes
  when: ansible_distribution == "CentOS"

- name: Add ELK RPM key (CentOS)
  rpm_key:
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
  when: ansible_distribution == "CentOS"

- name: Add ELK Repository (CentOS)
  yum_repository:
    name: elasticsearch-7.x
    description: Adds repository key
    baseurl: https://artifacts.elastic.co/packages/7.x/yum
    gpgcheck: True
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
  when: ansible_distribution == "CentOS"

- name: Install Elasticsearch (CentOS)
  yum:
    name: elasticsearch
    state: latest
    update_cache: yes
  when: ansible_distribution  == "CentOS"
